AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: DynamoDB Table

Resources:
  AdminAccountsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: AdminAccounts
      AttributeDefinitions:
        - AttributeName: adminAccountUID
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: adminAccountUID
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: email-index
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
