AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: DynamoDB Table

Resources:
  SiteConfigTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SiteConfig
      AttributeDefinitions:
        - AttributeName: code
          AttributeType: S
      KeySchema:
        - AttributeName: code
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # CategoryTable:
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: Category
  #     AttributeDefinitions:
  #       - AttributeName: id
  #         AttributeType: S
  #     KeySchema:
  #       - AttributeName: id
  #         KeyType: HASH
  #     BillingMode: PAY_PER_REQUEST

  # ProductTable:
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: Product
  #     AttributeDefinitions:
  #       - AttributeName: id
  #         AttributeType: S
  #       - AttributeName: categoryId
  #         AttributeType: S
  #     KeySchema:
  #       - AttributeName: id
  #         KeyType: HASH
  #     GlobalSecondaryIndexes:
  #       - IndexName: categoryId-index
  #         KeySchema:
  #           - AttributeName: categoryId
  #             KeyType: HASH
  #         Projection:
  #           ProjectionType: ALL
  #     BillingMode: PAY_PER_REQUEST
