AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Functions Cloudformation

Parameters:
  LambdaLayerArn:
    Type: String
  GetSiteConfigRoleArn:
    Type: String
  GetCategoriesRoleArn:
    Type: String
  GetProductsRoleArn:
    Type: String
  GetProductRoleArn:
    Type: String

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs18.x
    Handler: index.handler
    Layers:
      - !Ref LambdaLayerArn
    Environment:
      Variables:
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

Resources:
  GetSiteConfigFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetSiteConfigFunction
      CodeUri: ../dist/GetSiteConfig/
      Role: !Ref GetSiteConfigRoleArn
      Environment:
        Variables:
          SITE_CONFIG_TABLE_NAME: SiteConfig

  GetCategoriesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetCategoriesFunction
      CodeUri: ../dist/GetCategories/
      Role: !Ref GetCategoriesRoleArn
      Environment:
        Variables:
          CATEGORY_TABLE_NAME: Category
          COSMOS_SYSTEM_RESOURCES_BUCKET_NAME: cosmos-be-resources

  GetProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetProductsFunction
      CodeUri: ../dist/GetProducts/
      Role: !Ref GetProductsRoleArn
      Environment:
        Variables:
          PRODUCT_TABLE_NAME: Product
          COSMOS_SYSTEM_RESOURCES_BUCKET_NAME: cosmos-be-resources

  GetProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetProductFunction
      CodeUri: ../dist/GetProduct/
      Role: !Ref GetProductRoleArn
      Environment:
        Variables:
          PRODUCT_TABLE_NAME: Product
          COSMOS_SYSTEM_RESOURCES_BUCKET_NAME: cosmos-be-resources

Outputs:
  GetSiteConfigFunctionArn:
    Value: !GetAtt GetSiteConfigFunction.Arn
  GetCategoriesFunctionArn:
    Value: !GetAtt GetCategoriesFunction.Arn
  GetProductsFunctionArn:
    Value: !GetAtt GetProductsFunction.Arn
  GetProductFunctionArn:
    Value: !GetAtt GetProductFunction.Arn
