AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Functions Cloudformation

Parameters:
  GetSiteConfigRoleArn:
    Type: String

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs16.x
    Handler: index.handler
    Layers:
      - !Ref LambdaLayerArn
    Environment:
      Variables:
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

Resources:
  GetSiteConfigFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetSiteConfigFunction
      CodeUri: ../dist/GetSiteConfig/
      Role: !Ref GetSiteConfigRoleArn
      Environment:
        Variables:
          SITE_CONFIG_TABLE_NAME: SiteConfig

Outputs:
  GetSiteConfigFunctionArn:
    Value: !GetAtt GetSiteConfigFunction.Arn
