AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Cloudformation

Parameters:
  CosmosApiGateway:
    Type: String
  GetSiteConfigFunctionArn:
    Type: String

Resources:
  GetSiteConfigPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref GetSiteConfigFunctionArn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${CosmosApiGateway}/*/GET/site-config
