openapi: 3.0.0
info:
  title: Cosmos System
  version: 0.0.1

tags:
  - name: Site Configuration
    description: Everything about site configuration
  - name: Category
    description: Everything about category
  - name: Product
    description: Everything about product

paths:
  /site-config:
    get:
      tags:
        - Site Configuration
      operationId: GetSiteConfigFunction
      summary: Get site config
      description: Get site config information
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  siteName:
                    type: string
                    description: Site name
                  siteInformation:
                    type: object
                    description: Site information detail
                    properties:
                      description:
                        type: string
                        description: Site description
                      address:
                        type: string
                        description: Site address
                      telephone:
                        type: string
                        description: Site telephone
                      email:
                        type: string
                        description: Site email
                  siteSocialMedia:
                    type: object
                    description: Site social media
                    properties:
                      facebook:
                        type: string
                        description: Facebook social link
        "400":
          description: Error operation
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/ParameterError"
                  - $ref: "#/components/schemas/InternalError"
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        passthroughBehavior: when_no_templates
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CosmosFunctions.Outputs.GetSiteConfigFunctionArn}/invocations

  /categories:
    get:
      tags:
        - Auth
      operationId: GetCategoriesFunction
      summary: Get Categories
      description: Get Categories
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: Category ID
                        name:
                          type: string
                          description: Category name
                        description:
                          type: string
                          description: Category description
                        image:
                          type: string
                          description: Category preview image
                        subCategory:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: string
                                description: Category ID
                              name:
                                type: string
                                description: Category name
                              description:
                                type: string
                                description: Category description
                              image:
                                type: string
                                description: Category preview image
        "400":
          description: Error operation
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/ParameterError"
                  - $ref: "#/components/schemas/InternalError"
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        passthroughBehavior: when_no_templates
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CosmosFunctions.Outputs.GetCategoriesFunctionArn}/invocations

  /products:
    get:
      tags:
        - Product
      operationId: GetProductsFunction
      summary: GetProducts
      description: GetProducts
      parameters:
        - in: query
          name: categoryId
          schema:
            type: string
          description: |
            Filter products by category
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: Product ID
                        name:
                          type: string
                          description: Product name
                        image:
                          type: string
                          description: Product image url
                        categoryId:
                          type: string
                          description: Product category ID
        "400":
          description: Error operation
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/ParameterError"
                  - $ref: "#/components/schemas/InternalError"
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        passthroughBehavior: when_no_templates
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CosmosFunctions.Outputs.GetProductsFunctionArn}/invocations

  /products/{productId}:
    get:
      tags:
        - Product
      operationId: GetProductFunction
      summary: GetProduct
      description: GetProduct
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
          description: Product ID
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Product ID
                  name:
                    type: string
                    description: Product name
                  image:
                    type: string
                    description: Product image url
                  description:
                    type: string
                    description: Product description
                  powerRange:
                    type: string
                    description: Product power range
                  gridSystem:
                    type: string
                    nullable: true
                    description: Product grid system
                  workingWay:
                    type: string
                    nullable: true
                    description: Product working way
                  suitableArea:
                    type: string
                    description: Product suitable area
                  catalogue:
                    type: string
                    description: Product catalogue url
                  performanceCharacteristics:
                    type: array
                    items:
                      type: object
                      properties:
                        icon:
                          type: string
                          description: Performance characteristic icon
                        title:
                          type: string
                          description: Performance characteristic title
                        description:
                          type: string
                          description: Performance characteristic description
                  diagrams:
                    type: array
                    items:
                      type: object
                      properties:
                        icon:
                          type: string
                          description: Diagram icon
                        title:
                          type: string
                          description: Diagram title
                        description:
                          type: string
                          description: Diagram description
                  categoryId:
                    type: string
                    description: Product category ID
        "400":
          description: Error operation
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/ParameterError"
                  - $ref: "#/components/schemas/DataNotFound"
                  - $ref: "#/components/schemas/InternalError"
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        passthroughBehavior: when_no_templates
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CosmosFunctions.Outputs.GetProductFunctionArn}/invocations

components:
  schemas:
    # Success Schemas
    Success:
      description: Success
      type: object
      properties:
        message:
          type: string
          example: success

    # End Success Schemas

    # Error Schemas
    ParameterError:
      description: Paramter error
      type: object
      properties:
        errorCode:
          type: integer
          example: 10
        errorMessage:
          type: string
          example: Parameter error

    DataNotFound:
      description: Data not found
      type: object
      properties:
        errorCode:
          type: integer
          example: 20
        errorMessage:
          type: string
          example: Data not found

    InternalError:
      description: Internal error
      type: object
      properties:
        errorCode:
          type: integer
          example: 901
        errorMessage:
          type: string
          example: Internal error
    # End Error Schemas

  securitySchemes:
    api_key:
      type: apiKey
      name: Authorization
      in: header
