openapi: 3.0.0
info:
  title: Cosmos System
  version: 0.0.1

tags:
  - name: Site Configuration
    description: Everything about site configuration
  - name: Category
    description: Everything about category

paths:
  /site-config:
    get:
      tags:
        - Site Configuration
      operationId: GetSiteConfigFunction
      summary: Get site config
      description: Get site config information
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  siteName:
                    type: string
                    description: Site name
                  siteInformation:
                    type: object
                    description: Site information detail
                    properties:
                      description:
                        type: string
                        description: Site description
                      address:
                        type: string
                        description: Site address
                      telephone:
                        type: string
                        description: Site telephone
                      email:
                        type: string
                        description: Site email
                  siteSocialMedia:
                    type: object
                    description: Site social media
                    properties:
                      facebook:
                        type: string
                        description: Facebook social link
        "400":
          description: Error operation
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/ParameterError"
                  - $ref: "#/components/schemas/InternalError"
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        passthroughBehavior: when_no_templates
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CosmosFunction.Outputs.GetSiteConfigFunctionArn}/invocations

  /categories:
    get:
      tags:
        - Auth
      operationId: GetCategoriesFunction
      summary: Get Categories
      description: Get Categories
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  data: 
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: Category ID
                        name:
                          type: string
                          description: Category name
                        description:
                          type: string
                          description: Category description
                        image:
                          type: string
                          description: Category preview image
                        subCategory:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: string
                                description: Category ID
                              name:
                                type: string
                                description: Category name
                              description:
                                type: string
                                description: Category description
                              image:
                                type: string
                                description: Category preview image
        "400":
          description: Error operation
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/ParameterError"
                  - $ref: "#/components/schemas/InternalError"
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        passthroughBehavior: when_no_templates
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CosmosFunctions.Outputs.GetCategoriesFunctionArn}/invocations

components:
  schemas:
    # Success Schemas
    Success:
      description: Success
      type: object
      properties:
        message:
          type: string
          example: success

    # End Success Schemas

    # Error Schemas
    ParameterError:
      description: Paramter error
      type: object
      properties:
        errorCode:
          type: integer
          example: 10
        errorMessage:
          type: string
          example: Parameter error

    WrongUsernamePassword:
      description: Username or Password is wrong
      type: object
      properties:
        errorCode:
          type: integer
          example: 20
        errorMessage:
          type: string
          example: Username or Password is wrong

    InternalError:
      description: Internal error
      type: object
      properties:
        errorCode:
          type: integer
          example: 901
        errorMessage:
          type: string
          example: Internal error
    # End Error Schemas

  securitySchemes:
    api_key:
      type: apiKey
      name: Authorization
      in: header
