name: Main control CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml

  cd:
    needs: [ci]
    if: github.event_name == 'push'
    uses: ./.github/workflows/cd.yaml
    with:
      AWS_REGION: ap-southeast-1
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
